### ISSUE TITLE
Plotting with specific palette and multiline annotation trace render only one annotation

### ISSUE THREAD

**Issue by ilariasalutari** [Melkiades/CampaRi#22]
The following example is showing the problem (I am using an annotation trace with 3 lines). This works for whatever PROGIND file I use.
`sapphire_plot('PROGIDX_000000264003_320040snaps.dat', timeline=T, timeline_proportion=0.3, local_cut=F, horiz_lines_on_timeline=c(80010, 160020, 240030, 320040), return_plot=T, ann_trace = ann, specific_palette=c("#b47b00", "#000000"), rescaling_ann_col=F )`

**Comment by Melkiades** [comment]
Thank you for the indication. the bug has been fixed.
