### ISSUE TITLE
Setting the height of the annotation trace

### ISSUE THREAD

**Issue by ilariasalutari** [Melkiades/CampaRi#23]
I would like to set manually the baseline height of the annotation trace. Is it possible?

**Comment by Melkiades** [comment]
This feature is already present. Please use `ann_initial_point` with a value between 0 and 1 (it is a proportion).

e.g. (from vignette): 
`sapphire_plot('PROGIDX_000000000001.dat', return_plot = TRUE, local_cut = FALSE, ann_trace = ann, rescaling_ann_col=F, specific_palette= c("#b47b00", "#000000"), ann_initial_point=0.1)`
