### ISSUE TITLE
Legend with small colored boxes

### ISSUE THREAD

**Issue by ilariasalutari** [Melkiades/CampaRi#24]
I would like to plot a legend made of small boxes (with their titles), colored as the annotation trace to which it refers. For now it is only possible to plot a lateral bar scale, with colors that transition between those chosen in the annotation trace, by adding this function with ggplot2 :
` scale_fill_gradientn(colours = c( '#9350B9', '#99FFFF', '#7F7F7F', "#00FFFF", '#DAA520', '#008000', '#FF0000', '#000000'), na.value = "transparent", breaks=c(0,0.4,0.5,0.8, 1), labels=c("Unknown", "alpha3-10","Turn", "Bend"), limits=c(0,1))`

**Comment by Melkiades** [comment]
Now it is possible using a smart combination of the following keywords: 'plot_legend',  'legend_title', 'legend_labels', 'annotation_type' ('continuous' or 'discrete'). remember to put the palette you want for the annotation using 'specific_palette_annotation' with hex colors.
