### ISSUE TITLE
run_campari does not find campari executable

### ISSUE THREAD

**Issue by deb89** [Melkiades/CampaRi#26]
When running:
`run_campari(key_file_input = "nbu_simulation.key")`
I get the following error message:
`Looking for additional campari bin locations (exports) in ~/.bashrc file... found.
Looking for additional campari bin locations (exports) in ~/.bash_profile file... 
cat: /home/dgiordano/.bash_profile: No such file or directory
not found.
Looking for additional campari bin locations (aliases) in ~/.bash_profile file... 
cat: /home/dgiordano/.bash_profile: No such file or directory
not found.
Error in run_campari(key_file_input = "nbu_simulation.key") : 
  No campari (or camp_ncminer) executable found between the standard commands. Please install the library and alias the bin executables.
In addition: Warning message:
In run_campari(key_file_input = "nbu_simulation.key") :
  All the check for the simulation mode are shallow and the real error messages are delivered directly by the campari library.`

note that campari executable is in my PATH.
It would be nice to have the possibility to manually specify the campari executable in case run_campari() cannot find it.

**Comment by Melkiades** [comment]
Corrected. The option has been inserted (check campari_exe in the documentation).
