### ISSUE TITLE
Issue with basin recognition

### ISSUE THREAD

**Issue by deb89** [Melkiades/CampaRi#32]
running a simple nx = 50 on a 27k sapphire table is throwing this error:
`> basins_recognition(data = "PROGIDX_000000010129.dat", nx = 50)
Reading PROGIDX file...
Analysis of the dynamic trace...
Nbins on y is 50 
Error in sort(c(idxx.up.cl, idxx.down.cl)) : 
  object 'idxx.up.cl' not found`

**Comment by fcocin** [comment]
Issue solved within the last commit
