### ISSUE TITLE
basin recognition needs tests (also msm)

### ISSUE THREAD

**Issue by Melkiades** [Melkiades/CampaRi#33]
@fcocin please make the tests for your functions, so to avoid nasty bugs and uncaught sacks of unused code.

**Comment by Melkiades** [comment]
I do not want to push but the 600 untracked lines on basin_recognition are affecting the code coverage in a really negative way. This is easy and fast to fix.
![screenshot from 2017-10-31 12-18-42](https://user-images.githubusercontent.com/11279768/32221439-d49d5e2a-be35-11e7-9d48-21cb8f45792b.png)

**Comment by deb89** [comment]
I am not an expert but I think this work should be concluded the sooner possible. It is a pity that this is the only missing peace.

Have a nice work,
D.

**Comment by deb89** [comment]
I am not an expert but I think this work should be concluded the sooner possible. It is a pity that this is the only missing peace.

Have a nice work,
D.

**Comment by deb89** [comment]
I am not an expert but I think this work should be concluded the sooner possible. It is a pity that this is the only missing peace.

Have a nice work,
D.

**Comment by deb89** [comment]
I am not an expert but I think this work should be concluded the sooner possible. It is a pity that this is the only missing peace.

Have a nice work,
D.

**Comment by Melkiades** [comment]
Thanks for the feedback dear deb89. The first part (basin_recognition()) has been completed by @fcocin. I am eager to get the tests also for msm.

**Comment by fcocin** [comment]
Dear deb89,
today our developers committed to your kind request and tests on msm() have been just added.
Thanks for your feedback and we look forward to hearing your next suggestions. 

> ‘A meglio parola è chela ca se dice

CampaRi team
