### ISSUE TITLE
forecast instead of prospectr package for moving average

### ISSUE THREAD

**Issue by Melkiades** [Melkiades/CampaRi#36]
I personally advise using [forecast](https://cran.r-project.org/web/packages/forecast/index.html) function `ma()` instead of `movav()` from [prospectr](https://cran.r-project.org/web/packages/prospectr/index.html)
also because prospectr is not updated since 2014

**Comment by fcocin** [comment]
Many thanks for the advice Davide! Unfortunately the forecast package has no function for the Savitzky-Gollay filter :( . Thus we should rely on the prospectr anyway.
