### ISSUE TITLE
Problems with use_plotly option

### ISSUE THREAD

**Issue by deb89** [Melkiades/CampaRi#37]
If I use this option is not returning anything, while if I use it with a wrapper is getting me NO timeline.

**Comment by Melkiades** [comment]
use_plotly = T is now fully working. The absence of the timeline is actually due to a difference in standard sizes and transparency between ggplot2  and plotly. I advise to use the option size_points_on_timeline to >0.1 as workaround.

**Comment by Melkiades** [comment]
please install using: `devtools::install_github('Melkiades/CampaRi')`
